### ISSUE TITLE
[401] Error connecting to the API (https://api-uat.dwolla.com//customers?limit=10&offset=0)

### ISSUE THREAD

**Issue by developercakephp** [Dwolla/dwolla-swagger-php#1]
[401] Error connecting to the API (https://api-uat.dwolla.com//customers?limit=10&offset=0)

This error always came when i tried to feach customer list. below is my code.

DwollaSwagger\Configuration::$access_token = 'token';
        $apiClient = new DwollaSwagger\ApiClient("https://api-uat.dwolla.com/");
        $customersApi = new DwollaSwagger\CustomersApi($apiClient);
        $myCusties = $customersApi->_list(10,0);
        print_r($myCusties);exit;

**Comment by timbroder** [comment]
@developercakephp have you tried turning debug mode on? That helped me a lot

After you set your access token:

``` php
Configuration::$debug = 1;
```

**Comment by incentfit-product** [comment]
If you have a self-signed cert on localhost then you might be seeing this error

**Comment by dharabhatia** [comment]
Even I getting same error. 
@incentfit  How to identify I have self-signed cert on localhost. 

Fatal error: Uncaught exception 'DwollaSwagger\ApiException' with message '[404] Error connecting to the API (https://api-uat.dwolla.com/customers/customers)' in /opt/lampp/htdocs/dwollaswagger/vendor/dwolla/dwollaswagger/lib/ApiClient.php:308 Stack trace: #0 /opt/lampp/htdocs/dwollaswagger/vendor/dwolla/dwollaswagger/lib/CustomersApi.php(168): DwollaSwagger\ApiClient->callApi('/customers', 'POST', Array, Array, Array, Array) #1 /opt/lampp/htdocs/dwollaswagger/vendor/customer.php(12): DwollaSwagger\CustomersApi->create(Array) #2 {main} thrown in /opt/lampp/htdocs/dwollaswagger/vendor/dwolla/dwollaswagger/lib/ApiClient.php on line 308

**Comment by timbroder** [comment]
@dharabhatia we've setup free local certs using https://letsencrypt.org/ is it's self-signed that's the issue (won't fix the underlying problem if it's that, but might be a quick workaround for you)

**Comment by dharabhatia** [comment]
Thanks for you suggestion but its not a solution.

**Comment by cjcodes** [comment]
In case this hasn't yet been resolved (and for documentation purposes), @dharabhatia, it looks like you've initialized the API something along these lines: `new DwollaSwagger\ApiClient("https://api-uat.dwolla.com/customers");` since your ApiClient is attempting to POST to /customers/customers.

Note @developercakephp's code above: the ApiClient (and all sub-clients) are based off the root api: `https://api-uat.dwolla.com/`

**Comment by timbroder** [comment]
Addendum to @cjcodes's note above, top level is now ```https://api-sandbox.dwolla.com``` rather than ```api-uat```
