### ISSUE TITLE
Missing Beneficial owners

### ISSUE THREAD

**Issue by nhatlang19** [Dwolla/dwolla-swagger-php#21]
There are some changes in Dwolla, 
https://docsv2.dwolla.com/#create-a-customer
https://docsv2.dwolla.com/#beneficial-owners
Can you update it?

**Comment by spencerhunter** [comment]
Hi @nhatlang19 , I am working on pushing these updates today and will post back when you can grab the latest version.

**Comment by spencerhunter** [comment]
@nhatlang19 , closing as this has been fixed with the latest release. https://github.com/Dwolla/dwolla-swagger-php/releases/tag/1.0.17
