### ISSUE TITLE
Missing ; in createCustomer.php line 118

### ISSUE THREAD

**Issue by nhatlang19** [Dwolla/dwolla-swagger-php#25]
line 77:
'website' => 'website',
'controller' => 'object' <= should be 'controller' not 'object'

line 118:
$this->controller = $data["controller"]
Missing ;

**Comment by spencerhunter** [comment]
Ah, thanks for pointing this out @nhatlang19 ! I'll push up a patch fix for this here in a little bit. 😄

**Comment by spencerhunter** [comment]
Should be fixed with latest version. Thanks again!
