### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by dharabhatia** [Dwolla/dwolla-swagger-php#7]
When I creating a customer it throw me. 
 Fatal error: Call to undefined method DwollaSwagger\DocumentsApi::create() in /opt/lampp/htdocs/dwollaswagger/customer.php on line 10

Code I have written
DwollaSwagger\Configuration::$access_token = '';
$apiClient = new DwollaSwagger\ApiClient("https://api-uat.dwolla.com/");
$customersApi = new DwollaSwagger\DocumentsApi($apiClient);

$new_customer = $customersApi->create([
  'firstName' => 'Bob',
  'lastName' => 'Merchant',
  'email' => 'bmerchant@nomail.net',
  'ipAddress' => '127.0.0.1'
]);

Please help me out to resolve it.

**Comment by dharabhatia** [comment]
I have correct the code. In API I need to call https://api-uat.dwolla.com/customers That I did but give me error .

 Fatal error: Uncaught exception 'DwollaSwagger\ApiException' with message '[404] Error connecting to the API (https://api-uat.dwolla.com/customers/customers)' in /opt/lampp/htdocs/dwollaswagger/vendor/dwolla/dwollaswagger/lib/ApiClient.php:308 Stack trace: #0 /opt/lampp/htdocs/dwollaswagger/vendor/dwolla/dwollaswagger/lib/CustomersApi.php(168): DwollaSwagger\ApiClient->callApi('/customers', 'POST', Array, Array, Array, Array) #1 /opt/lampp/htdocs/dwollaswagger/vendor/customer.php(12): DwollaSwagger\CustomersApi->create(Array) #2 {main} thrown in /opt/lampp/htdocs/dwollaswagger/vendor/dwolla/dwollaswagger/lib/ApiClient.php on line 308

**Comment by lochnesh** [comment]
This issue is being supported on our support forum. 

https://discuss.dwolla.com/t/dwolla-swagger-uncaught-exception-dwollaswagger-apiexception-with-message-404-error-connecting-to-the-api/2819

This issue will be closed.
