### ISSUE TITLE
API discrepancy for Transfer Fees

### ISSUE THREAD

**Issue by cjcodes** [Dwolla/dwolla-swagger-php#8]
`TransfersApi->getFeesBySource($id)` converts the response from the API to a `TransferListResponse`, which expects input of format:

``` json
{
  "_links": {},
  "_embedded": {},
  "total": 123
}
```

However, the response from the API is of this format:

``` json
{
  "transactions": [
    {
      "_links": {},
      ...
    }
  ],
  "total": 123
}
```

This leads to a response that has the correct total, but no fee transfers are being populated.

**Comment by cjcodes** [comment]
Is this something I can submit a PR against, or is this library generated exclusively via Swagger?

**Comment by spencerhunter** [comment]
Hey @cjcodes , Thanks for bringing this to our attention. It looks like the API response on this call doesn't match the format that is returned on other endpoints that have embedded list. We're working on making an update to the API that'll be non-breaking, which will allow you to easily transition to the new response. Once this is done, we'll work on regenerating the client via swagger-codegen.

**Comment by spencerhunter** [comment]
@cjcodes This should now be fixed in the latest version. TransferListResponse was replaced with FeesBySourceResponse.
