### ISSUE TITLE
New getAccountFundingSources "removed" parameter

### ISSUE THREAD

**Issue by AdamEsterle** [Dwolla/dwolla-swagger-php#9]
Does not work
$fundingSourceApi->getAccountFundingSources($account_id, false);

Does Work
$fundingSourceApi->getAccountFundingSources($account_id, "false");

I feel like that should be fixed? And be able to accept a primitive boolean since you may be doing it as a variable
$fundingSourceApi->getAccountFundingSources($account_id, $shouldRemove);

Thoughts?

**Comment by cjcodes** [comment]
Additionally, this parameter used to be optional (`$removed = false` in the function definition), but is now required on this and getCustomerFundingSources.

**Comment by snickbit** [comment]
I just set it to null, that stops the removed parameter from appearing in the request.
